name: Build & Run

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        toolchain: [stable] #, beta, nightly]

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}

      - uses: Swatinem/rust-cache@v1

      - name: Run
        uses: actions-rs/cargo@v1.0.3
        with:
          command: run
          toolchain: ${{matrix.toolchain}}
          args: --release --verbose
