name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        for d in 2020/*/
        do
            (cd "$d" && test -r Cargo.toml && cargo check --verbose )
        done

    - name: Run tests
      run: |
        for d in 2020/*/
        do
            (cd "$d" && test -r Cargo.toml && cargo test --verbose )
        done
